Hw18 annotation
YuraBondarenko/jv-create-annotation pull request #1
Opened 2021-01-07 17:04 UTC by YuraBondarenko

2021-01-07 17:31 UTC, antoniukivan approved these changes

2021-01-08 09:23 UTC, KseniiaMakarova requested changes

2021-01-08 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
what about ArrayIndexOutOfBoundException? let’s catch it here as well

2021-01-08 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.add(bet);
let’s save  the bet if it is not null

2021-01-08 09:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/UserDaoImpl.java
> +    public List<User> getAllUser() {
```suggestion
    public List<User> getAllUsers() {
```

2021-01-08 14:19 UTC, KseniiaMakarova approved these changes

2021-01-10 11:50 UTC, merged